
name: nlvr2
dataset_dir: ${data_dir}/datasets/nlvr2

num_negatives_per_example: 0

task_loss_scale: 1
prune_no_sparsity: False
prune_loss_scale: 0
grdcm_loss_scale: 0
grdcm_bce: False
cnt_loss_scale: 0
logits_loss_scale: 1
states_loss_scale: 0
text_loss_scale: 0
attn_loss_scale: 0
ib_kl: False
grdcm_ctr: False
gradcam_layer: -1

max_text_len: 40
tokenizer: bert-base-uncased
dataset_target: pumer.dataset.dataset_nlvr2.Nlvr2Dataset
image_size: 384
is_clip: False

image_db_dir: /tmp/lmdb
train_db: nlvr2-train.lmdb
dev_db: nlvr2-dev.lmdb
test_db: nlvr2-test1.lmdb

train_file: train.json
dev_file: dev.json
test_file: test1.json

predictions_output_file: ${results_dir}/preds/${task.test_file}.${model.ckpt}-preds.csv

eval_dataset:
  _target_: ${task.dataset_target}
  tokenizer: ${task.tokenizer}
  max_text_len: ${task.max_text_len}
  use_randaug: False
  image_size: ${task.image_size}
  is_clip: ${task.is_clip}
  dataset_file: ${task.dataset_dir}/${task.dev_file}
  image_db_path: ${task.image_db_dir}/${task.dev_db}

predict_dataset: ${task.test_dataset}

test_dataset:
  _target_: ${task.dataset_target}
  tokenizer: ${task.tokenizer}
  max_text_len: ${task.max_text_len}
  use_randaug: False
  image_size: ${task.image_size}
  is_clip: ${task.is_clip}
  dataset_file: ${task.dataset_dir}/${task.test_file}
  image_db_path: ${task.image_db_dir}/${task.test_db}

train_dataset:
  _target_: ${task.dataset_target}
  tokenizer: ${task.tokenizer}
  max_text_len: ${task.max_text_len}
  use_randaug: True
  image_size: ${task.image_size}
  is_clip: ${task.is_clip}
  dataset_file: ${task.dataset_dir}/${task.train_file}
  image_db_path: ${task.image_db_dir}/${task.train_db}
